# -*- coding: utf-8 -*-
"""Test_CPPN_Show_Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMfiffNIM5xzqHsLgZu-6bEVf-KlaFI3
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import random



# ==== STEP 1: Load FashionMNIST ====
transform = transforms.ToTensor()
dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
#data_loader = DataLoader(dataset, batch_size=1, shuffle=True)  # one image for simplicity
#images, _ = next(iter(data_loader))  # [1, 1, 28, 28]


# choosing index is only for showing one image
# Pick a random index or set a fixed one
#index = random.randint(0, len(dataset) - 1)
index = 10319  # Uncomment to fix a specific index


# get the choosen image
image, label = dataset[index]
images = image.unsqueeze(0)  # [1, 1, 28, 28]


# ==== STEP 2: Transform image to CPPN coordinates ====
def image_to_cppn_coords(images, epsilon=1e-6):
    B, C, H, W = images.shape   # (1, 1, 28, 28) format: [Batch, Channels, Height, Width], here Batch=1, channels=1 (fashinmnist), Height → number of pixels in vertical dimension, Width → number of pixels in horizontal dimension

    # Flatten pixel intensities: [B, C, H, W] → [B, H*W*C]
    pixels = images.permute(0, 2, 3, 1).reshape(B, H * W * C)  # [B, HWC]

    # Compute Y = log(p + epsilon)
    y = -torch.log(pixels + epsilon)

    # Compute spatial index X = i * W + j (same for each image)
    spatial_index = torch.arange(H * W, dtype=torch.float32, device=images.device).repeat(C)  # [H*W*C]
    x = spatial_index.unsqueeze(0).expand(B, -1)  # [B, H*W*C]

    # Stack X and Y
    coords = torch.stack([x, y], dim=-1)  # [B, H*W*C, 2]
    return coords, H, W, C



#coords, H, W, C = image_to_cppn_coords(images)  # coords: [1, 784, 2]



# ==== STEP 3: Define a simple CPPN ====
class SimpleCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 2]
        #x = torch.sin(self.fc1(coords))
        x = torch.relu(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        out = torch.sigmoid(self.fc3(x))  # Output in [0, 1]
        return out



cppn = SimpleCPPN()
#cppn = EnhancedCPPN()

# ==== STEP 4: Generate output from CPPN ====
cppn_output = cppn(coords)  # [1, HWC, 1]
image_generated = cppn_output.view(1, C, H, W).detach()  # [1, 1, 28, 28]



# ==== STEP 5: Plot original and CPPN output ====
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
axs[0].imshow(images[0, 0].cpu(), cmap="gray")
axs[0].set_title(f"Original Image\Index: {index}")
axs[0].axis("off")

axs[1].imshow(image_generated[0, 0].cpu(), cmap="gray")
axs[1].set_title("CPPN Output")
axs[1].axis("off")

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# ==== STEP 1: Set seed and load FashionMNIST deterministically ====
torch.manual_seed(42)  # Set seed for reproducibility

transform = transforms.ToTensor()
dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
index = 10319  # choose any index
image, label = dataset[index]
images = image.unsqueeze(0)  # shape: [1, 1, 28, 28]

# ==== STEP 2: Transform image to CPPN coordinates ====
def image_to_cppn_coords(images, epsilon=1e-6):
    B, C, H, W = images.shape
    pixels = images.permute(0, 2, 3, 1).reshape(B, H * W * C)
    y = -torch.log(pixels + epsilon)  # make y always positive
    spatial_index = torch.arange(H * W, dtype=torch.float32, device=images.device).repeat(C)
    x = spatial_index.unsqueeze(0).expand(B, -1)
    coords = torch.stack([x, y], dim=-1)
    return coords, H, W, C

#coords, H, W, C = image_to_cppn_coords(images)

# ==== STEP 3: Define a simple CPPN ====
class SimpleCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 2]
        x = torch.relu(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        out = torch.sigmoid(self.fc3(x))
        return out

class EnhancedCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=128, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, hidden_dim)
        self.fc4 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 2]
        x = torch.sin(self.fc1(coords))      # spatial structure
        x = torch.tanh(self.fc2(x))          # smooth nonlinearity
        x = F.leaky_relu(self.fc3(x), 0.2)   # non-symmetric
        out = torch.sigmoid(self.fc4(x))     # intensity output
        return out


cppn = SimpleCPPN()
#cppn = EnhancedCPPN()
cppn_output = cppn(coords)  # [1, HWC, 1]
image_generated = cppn_output.view(1, C, H, W).detach()

# ==== STEP 5: Plot original and CPPN output ====
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
axs[0].imshow(images[0, 0].cpu(), cmap="gray")
axs[0].set_title("Original Image")
axs[0].axis("off")

axs[1].imshow(image_generated[0, 0].cpu(), cmap="gray")
axs[1].set_title("CPPN Output")
axs[1].axis("off")

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# ==== STEP 1: Set seed and load CIFAR-10 deterministically ====
torch.manual_seed(42)

transform = transforms.ToTensor()
dataset = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
index = 10319  # choose any index
image, label = dataset[index]
images = image.unsqueeze(0)  # shape: [1, 3, 32, 32]

# ==== STEP 2: Transform image to CPPN coordinates ====
c=3
def image_to_cppn_coords_rgb(images, epsilon=1e-6):
    B, C, H, W = images.shape  # e.g., [1, 3, 32, 32]

    coords_list = []
    intensity_list = []

    for c in range(C):  # Loop over R, G, B
        # Extract channel c
        channel_img = images[:, c:c+1, :, :]  # shape: [B, 1, H, W]
        pixels = channel_img.view(B, -1)      # shape: [B, H*W]
        y = -torch.log(pixels + epsilon)      # positive intensities

        # Generate spatial grid for x and y
        xs = torch.linspace(-1, 1, W, device=images.device)
        ys = torch.linspace(-1, 1, H, device=images.device)
        grid_y, grid_x = torch.meshgrid(ys, xs, indexing="ij")  # shape: [H, W]

        # Flatten and repeat for batch
        grid_x = grid_x.flatten().unsqueeze(0).repeat(B, 1)  # [B, H*W]
        grid_y = grid_y.flatten().unsqueeze(0).repeat(B, 1)

        # Channel index feature normalized to [-1, 1]
        ch_idx = torch.full_like(grid_x, fill_value=(c / (C - 1)) * 2 - 1)  # -1, 0, 1

        # Concatenate coordinate vectors: [x, y, ch]
        coords = torch.stack([grid_x, grid_y, ch_idx], dim=-1)  # [B, H*W, 3]

        coords_list.append(coords)
        intensity_list.append(y.unsqueeze(-1))  # [B, H*W, 1]

    # Concatenate across channels
    all_coords = torch.cat(coords_list, dim=1)     # [B, H*W*C, 3]
    all_intensities = torch.cat(intensity_list, dim=1)  # [B, H*W*C, 1]

    return all_coords, all_intensities, H, W, C



# ==== STEP 3: Define a simple CPPN ====
class SimpleCPPN(nn.Module):
    def __init__(self, input_dim=3, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 3]
        x = torch.relu(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        out = torch.sigmoid(self.fc3(x))
        return out

cppn = SimpleCPPN()

# ==== STEP 4: Run CPPN and reconstruct image ====
coords, intensities, H, W, C = image_to_cppn_coords_rgb(images)
cppn_output = cppn(coords)  # returns [B, H*W*C, 1]
#image_generated = cppn_output.view(1, C, H, W)
image_generated = cppn_output.view(1, C, H, W).detach()


# ==== STEP 5: Plot original and CPPN output ====
fig, axs = plt.subplots(1, 2, figsize=(8, 4))

# Plot original image (RGB)
axs[0].imshow(images[0].permute(1, 2, 0).cpu())
axs[0].set_title("Original CIFAR-10")
axs[0].axis("off")

# Plot CPPN output
axs[1].imshow(image_generated[0].permute(1, 2, 0).cpu())
axs[1].set_title("CPPN Output")
axs[1].axis("off")

plt.tight_layout()
plt.show()