# -*- coding: utf-8 -*-
"""test_CPPN_LeNet

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quyhLslJ3sJ8piqNF-pg-We-YuyxPnnW
"""

import torch
import torch.nn as nn
import torch.nn.init as init
import torch.nn.functional as F

import torchvision.models as torch_models

import torch.optim as optim
from torch.utils.data import random_split, DataLoader, TensorDataset
from torchvision import datasets, transforms

import time
from datetime import datetime
import pytz

import numpy as np
import random
import math

import matplotlib.pyplot as plt



class LeNet(nn.Module):
    def __init__(self, input_channels, pretrained, num_classes):
        super(LeNet, self).__init__()

        # Convolutional Layers
        self.conv1 = nn.Conv2d(input_channels, 6, kernel_size=5, stride=1, padding=2)  # Output: 6x32x32
        self.pool = nn.AvgPool2d(kernel_size=2, stride=2)  # Pooling Layer: Output: 6x16x16
        self.conv2 = nn.Conv2d(6, 16, kernel_size=5, stride=1)  # Output: 16x12x12

        # Fully Connected Layers
        feature_map_size = 5 if input_channels == 1 else 6

        self.fc1 = nn.Linear(16 * feature_map_size * feature_map_size, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, num_classes)

        # Activation Function
        self.sigmoid = nn.Sigmoid()
        self.flatten = nn.Flatten()

        # Initialize weights
        if pretrained:
          self.load_pretrained_weights()


    def forward(self, x):
        x = self.sigmoid(self.conv1(x))  # Convolution 1 + Activation
        x = self.pool(x)                    # Pooling
        x = self.sigmoid(self.conv2(x))  # Convolution 2 + Activation
        x = self.pool(x)                   # Pooling again
        x = self.flatten(x)                 # Flatten
        x = self.sigmoid(self.fc1(x))    # Fully Connected 1 + Activation
        x = self.sigmoid(self.fc2(x))    # Fully Connected 2 + Activation
        x = self.fc3(x)                     # Fully Connected 3 (Output Layer)
        return x




# settings
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# experiments settings
model_class = LeNet

# initialize settings
pretrained = False
random_seed = 0
random.seed(0)
torch.manual_seed(0)
if torch.cuda.is_available(): torch.cuda.manual_seed(0)

# train settings
num_epochs = 30
validation = True
learning_rate = 0.05
momentum = 0.9
scheduler = False
step_size = 30
gamma = 0.1
temperature = 4
alpha = 0.9

# dataset settings
dataset_name= "fashionmnist"
K = 10
batch_size = 64
input_channels =1
num_classes = 10
train_size_percent = .80
val_size_percent = .10
test_size_percent = .10


def initialize_model():

    if pretrained:
        model = model_class(input_channels, pretrained, num_classes).to(device)
    else:
        model = model_class(input_channels, pretrained, num_classes).to(device)
    return model



def accuracy(model, test_loader):
  model.eval()
  correct = 0
  total = 0
  with torch.no_grad():
    for images, labels in test_loader:
      images, labels = images.to(device), labels.to(device)
      outputs = model(images)
      _, predicted = torch.max(outputs, 1)
      total += labels.size(0)
      correct += (predicted == labels).sum().item()

  accuracy = 100 * correct / total
  return accuracy


def train(model, train_loader, val_loader, num_epochs, scheduler, validation):

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum)

    if scheduler:
        scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size, gamma)

    for epoch_idx in range(num_epochs):
        model.train()
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

        if scheduler:
            scheduler.step()

        if validation:
            val_accuracy = accuracy(model, val_loader)
            print(f"Epoch {epoch_idx + 1}/{num_epochs}, val_accuracy: {round(val_accuracy, 2)}")

    return model


def load_dataset(dataset_name, batch_size):

    # Dataset transformations
    if dataset_name.lower() in ["mnist", "fashionmnist"]:
        transform = transforms.Compose([transforms.ToTensor()])
    else:  # CIFAR datasets
        transform = transforms.Compose([
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))])

    # Load dataset
    if dataset_name.lower() == "mnist":
        dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
    elif dataset_name.lower() == "fashionmnist":
        dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
    elif dataset_name.lower() == "cifar_10":
        dataset = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
    elif dataset_name.lower() == "cifar_100":
        dataset = datasets.CIFAR100(root="./data", train=True, download=True, transform=transform)
    else:
        raise ValueError(f"Unsupported dataset: {dataset_name}. Please choose 'mnist', 'fashionmnist', 'cifar_10', or 'cifar_100'.")

    # Create a DataLoader for the full dataset
    data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    return dataset, data_loader


def split_dataset(dataset, batch_size, train_size_percent, val_size_percent):

    # Calculate split sizes
    train_size = int(train_size_percent * len(dataset))
    val_size = int(val_size_percent * len(dataset))
    test_size = len(dataset) - train_size - val_size

    # Split dataset
    train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])

    # Create DataLoaders
    generator = torch.Generator() # added to test if the result will be the same
    generator.manual_seed(random_seed)  # added to test if the result will be the same

    train_loader = DataLoader(train_dataset, generator=generator, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, generator=generator, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, generator=generator, batch_size=batch_size, shuffle=False)


    return train_loader, val_loader, test_loader

# 1. load original dataset
dataset, data_loader = load_dataset(dataset_name=dataset_name, batch_size=batch_size)
train_loader, val_loader, test_loader = split_dataset(dataset=dataset, batch_size=batch_size, train_size_percent=train_size_percent, val_size_percent=val_size_percent)

model = initialize_model()
teacher = train(model, train_loader, val_loader, num_epochs=30, scheduler=False, validation=True)
print(accuracy(teacher, test_loader))


torch.save(teacher.state_dict(), "/content/drive/My Drive/models/lenet_teacher")

from google.colab import drive
drive.mount('/content/drive')

# load teacher
teacher = initialize_model()
teacher.load_state_dict(torch.load("/content/drive/My Drive/models/lenet_teacher"))

# ==== STEP 2: Transform image to CPPN coordinates ====
def image_to_cppn_coords(images, epsilon=1e-6):
    B, C, H, W = images.shape
    pixels = images.permute(0, 2, 3, 1).reshape(B, H * W * C)
    y = -torch.log(pixels + epsilon)  # make y always positive
    spatial_index = torch.arange(H * W, dtype=torch.float32, device=images.device).repeat(C)
    x = spatial_index.unsqueeze(0).expand(B, -1)
    coords = torch.stack([x, y], dim=-1)
    return coords, H, W, C



# ==== STEP 3: Define a simple CPPN ====
class SimpleCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 2]
        x = torch.relu(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        out = torch.sigmoid(self.fc3(x))
        return out

def distillation_with_cppn(student, teacher, train_loader, optimizer, criterion, temperature, alpha):

    student.train()
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # === Generate CPPN input coordinates from images ===
        coords, H, W, C = image_to_cppn_coords(images)
        coords = coords.to(device)

        # === Generate images from CPPN ===
        cppn_output = cppn(coords)  # [B, H*W*C, 1]
        cppn_output = cppn_output.squeeze(-1)  # [B, H*W*C]
        cppn_output = cppn_output.view(-1, C, H, W).detach()  # Shape: [B, C, H, W]


        # Get teacher predictions
        teacher.eval()
        with torch.no_grad():
            teacher_logits = teacher(images)
            _, teacher_labels = torch.max(teacher_logits, dim=1)
            teacher_labels = teacher_labels.to(device)
            teacher_cppn_logits = teacher(cppn_output)


        # Student predictions on raw images
        student_logits = student(images)
        student_cppn_logits = student(cppn_output)

        # Compute distillation loss
        loss_soft = F.kl_div(F.log_softmax(student_logits / temperature, dim=1), F.softmax(teacher_logits / temperature, dim=1),reduction='batchmean') * (temperature ** 2)

        # Compute cppn loss
        loss_cppn = F.kl_div(F.log_softmax(student_cppn_logits / temperature, dim=1), F.softmax(teacher_cppn_logits / temperature, dim=1),reduction='batchmean') * (temperature ** 2)

        # Compute standard CE loss
        loss_hard = criterion(student_logits, labels)

        # Total loss: weighted sum
        loss = (1 - alpha) * loss_hard + alpha * ((loss_soft + loss_cppn)/2)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

# Student: learns from raw images
student = LeNet(input_channels=input_channels, pretrained=False, num_classes=num_classes).to(device)

cppn = SimpleCPPN().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(student.parameters(), lr=learning_rate, momentum=momentum)

num_epochs=30
for epoch in range(num_epochs):
    distillation_with_cppn(student, teacher, train_loader, optimizer, criterion, temperature=temperature, alpha=alpha)

    acc = accuracy(student, val_loader)
    print(f"Epoch {epoch+1}/{num_epochs}, Val Accuracy: {acc:.2f}%")


print(accuracy(student, test_loader))

def simple_distillation(student, teacher, train_loader, optimizer, criterion, temperature, alpha):

    student.train()
    for images, labels in train_loader:
        images, labels = images.to(device), labels.to(device)

        # Get teacher predictions
        teacher.eval()
        with torch.no_grad():
            teacher_logits = teacher(images)
            _, teacher_labels = torch.max(teacher_logits, dim=1)
            teacher_labels = teacher_labels.to(device)


        # Student predictions on raw images
        student_logits = student(images)

        # Compute distillation loss
        loss_soft = F.kl_div(F.log_softmax(student_logits / temperature, dim=1), F.softmax(teacher_logits / temperature, dim=1),reduction='batchmean') * (temperature ** 2)

        # Compute standard CE loss
        loss_hard = criterion(student_logits, labels)

        # Total loss: weighted sum
        loss = (1 - alpha) * loss_hard + alpha * loss_soft

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()


# Student: learns from raw images
student = LeNet(input_channels=input_channels, pretrained=False, num_classes=num_classes).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(student.parameters(), lr=learning_rate, momentum=momentum)

num_epochs=40
for epoch in range(num_epochs):
    simple_distillation(student, teacher, train_loader, optimizer, criterion, temperature=temperature, alpha=alpha)

    acc = accuracy(student, val_loader)
    print(f"Epoch {epoch+1}/{num_epochs}, Val Accuracy: {acc:.2f}%")


print(accuracy(student, test_loader))