# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bM3PQGigRLYBMspJ_65mZVMz9c6pvQqp
"""

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# Define a simple CPPN
class SimpleCPPN(nn.Module):
    def __init__(self, coord_dim=3, hidden_dim=64, output_dim=3):
        super(SimpleCPPN, self).__init__()
        self.fc1 = nn.Linear(coord_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):
        x = torch.sin(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))  # [0, 1] range for RGB
        return x

# Generate coordinate grid
def generate_coords(size):
    xs = torch.linspace(-1, 1, size)
    ys = torch.linspace(-1, 1, size)
    xv, yv = torch.meshgrid(xs, ys, indexing='ij')
    r = torch.sqrt(xv**2 + yv**2)
    coords = torch.stack([xv, yv, r], dim=-1).view(-1, 3)  # [H*W, 3]
    return coords

# Main execution
cppn = SimpleCPPN()
coords = generate_coords(32)
with torch.no_grad():
    rgb_output = cppn(coords).view(32, 32, 3).numpy()

# Show image
plt.imshow(rgb_output)
plt.axis('off')
plt.title("Toy RGB Image Generated by CPPN")
plt.show()

import torch
import torch.nn as nn
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import matplotlib.pyplot as plt

# Define a simple Conditional CPPN
class ConditionalCPPN(nn.Module):
    def __init__(self, coord_dim=3, cond_dim=10, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(coord_dim + cond_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords, cond):
        cond_expanded = cond.unsqueeze(1).expand(-1, coords.shape[1], -1)
        x = torch.cat([coords, cond_expanded], dim=-1)
        x = torch.sin(self.fc1(x))
        x = torch.tanh(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x

# Generate normalized (x, y, r) coordinate grid
def generate_coords(size):
    xs = torch.linspace(-1, 1, size)
    ys = torch.linspace(-1, 1, size)
    xv, yv = torch.meshgrid(xs, ys, indexing='ij')
    r = torch.sqrt(xv**2 + yv**2)
    coords = torch.stack([xv, yv, r], dim=-1).view(1, -1, 3)  # [1, H*W, 3]
    return coords

# Load FashionMNIST and get a single sample
transform = transforms.ToTensor()
dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
sample_image, sample_label = dataset[10]  # Get one image-label pair

# Create one-hot class embedding vector
cond_vector = torch.zeros(1, 10)
cond_vector[0, sample_label] = 1.0

# Generate grayscale image using CPPN conditioned on label
cppn = ConditionalCPPN()
coords = generate_coords(28)
with torch.no_grad():
    output = cppn(coords, cond_vector).view(28, 28).numpy()

# Plot original vs generated image
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
axs[0].imshow(sample_image.squeeze().numpy(), cmap='gray')
axs[0].set_title("Original FashionMNIST")
axs[0].axis('off')

axs[1].imshow(output, cmap='gray')
axs[1].set_title(f"CPPN (Label: {sample_label})")
axs[1].axis('off')

plt.tight_layout()
plt.show()

import torch
import numpy as np
import matplotlib.pyplot as plt


class ConditionalCPPN(nn.Module):
    def __init__(self, coord_dim=2, cond_dim=4, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(coord_dim + cond_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords, cond):
        # coords: [B, N, 2], cond: [B, cond_dim]
        cond_expanded = cond.unsqueeze(1).expand(-1, coords.size(1), -1)
        x = torch.cat([coords, cond_expanded], dim=-1)
        x = torch.sin(self.fc1(x))
        x = torch.tanh(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))
        return x  # [B, N, output_dim]



def generate_circle_coords(image_size=28, radius=None, center=None, num_points=1000):
    # Random radius and center if not provided
    if radius is None:
        radius = np.random.uniform(0.2, 0.5)  # radius in normalized [-1, 1] space
    if center is None:
        center = np.random.uniform(-0.5, 0.5, size=(2,))

    coords = []
    while len(coords) < num_points:
        x, y = np.random.uniform(-1, 1, 2)
        if (x - center[0])**2 + (y - center[1])**2 <= radius**2:
            coords.append((x, y))

    return torch.tensor(coords, dtype=torch.float32), radius, center

# Example usage
coords, radius, center = generate_circle_coords(num_points=500)

# Visualize
plt.figure(figsize=(4, 4))
plt.scatter(coords[:, 0], coords[:, 1], s=2)
circle = plt.Circle(center, radius, color='r', fill=False)
plt.gca().add_patch(circle)
plt.title(f"Circle Center={center}, Radius={round(radius, 2)}")
plt.axis('equal')
plt.grid(True)
plt.show()


batch_size = 1
num_points = coords.shape[0]  # e.g., 500
coords_input = coords.unsqueeze(0)  # shape: [1, 500, 2]

# Construct conditioning vector (e.g., center_x, center_y, radius, dummy)
cond = torch.tensor([[center[0], center[1], radius, 0.0]], dtype=torch.float32)  # shape: [1, 4]

# Forward pass
outputs = cppn(coords_input, cond)  # shape: [1, 500, output_dim]

import torch
import torch.nn as nn
import matplotlib.pyplot as plt

# === CPPN Definition ===
class CPPN(nn.Module):
    def __init__(self, input_dim=3, hidden_dim=32):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, 1)

    def forward(self, coords):
        x = torch.sin(self.fc1(coords))       # <-- sine activation here
        x = torch.tanh(self.fc2(x))           # regular tanh here
        x = torch.sigmoid(self.fc3(x))        # output between 0 and 1
        return x

# === Generate coordinates (x, y, r) ===
def generate_coords(size):
    coords = []
    r_values = []
    for y in range(size):
        for x in range(size):
            nx = (x / (size - 1)) * 2 - 1
            ny = (y / (size - 1)) * 2 - 1
            r = torch.sqrt(torch.tensor(nx**2 + ny**2))
            coords.append([nx, ny, r.item()])
            r_values.append(r.item())
    return torch.tensor(coords, dtype=torch.float32), torch.tensor(r_values).view(size, size)

# === Run the CPPN ===
image_size = 28
cppn = CPPN()
coords, r_image = generate_coords(image_size)  # coords: [784, 3]; r_image: [28, 28]
outputs = cppn(coords)                         # [784, 1]
output_image = outputs.view(image_size, image_size).detach().numpy()

# === Visualize input r and output image ===
fig, axs = plt.subplots(1, 2, figsize=(8, 4))

axs[0].imshow(r_image, cmap='viridis')
axs[0].set_title("Input: Radius r(x, y)")
axs[0].axis('off')

axs[1].imshow(output_image, cmap='gray')
axs[1].set_title("CPPN Output")
axs[1].axis('off')

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
from torchvision import datasets, transforms
import matplotlib.pyplot as plt

# === Feature Extractor (Encoder) ===
class Encoder(nn.Module):
    def __init__(self, output_dim=8):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Conv2d(1, 16, 3, stride=2, padding=1),  # 14x14
            nn.ReLU(),
            nn.Conv2d(16, 32, 3, stride=2, padding=1), # 7x7
            nn.ReLU(),
            nn.AdaptiveAvgPool2d(1),
            nn.Flatten(),
            nn.Linear(32, output_dim)
        )

    def forward(self, x):
        return self.encoder(x)

# === Conditional CPPN ===
class ConditionalCPPN(nn.Module):
    def __init__(self, coord_dim=3, cond_dim=8, hidden_dim=64):
        super().__init__()
        self.fc1 = nn.Linear(coord_dim + cond_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, 1)

    def forward(self, coords, cond):
        cond_expanded = cond.unsqueeze(1).expand(-1, coords.shape[1], -1)
        x = torch.cat([coords, cond_expanded], dim=-1)
        x = torch.sin(self.fc1(x))         # Sine helps with symmetry/pattern
        x = torch.tanh(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))     # Output in [0, 1]
        return x.squeeze(-1)

# === Generate coordinate grid ===
def generate_coords(size, batch_size):
    coords = []
    for y in range(size):
        for x in range(size):
            nx = (x / (size - 1)) * 2 - 1
            ny = (y / (size - 1)) * 2 - 1
            r = (nx**2 + ny**2) ** 0.5
            coords.append([nx, ny, r])
    coords = torch.tensor(coords, dtype=torch.float32)  # [H*W, 3]
    coords = coords.unsqueeze(0).repeat(batch_size, 1, 1)  # [B, H*W, 3]
    return coords

# === Load one FashionMNIST sample ===
transform = transforms.Compose([
    transforms.ToTensor()
])
dataset = datasets.FashionMNIST(root="./data", train=False, download=True, transform=transform)
image, label = dataset[1]  # change index for different clothes
image = image.unsqueeze(0)  # [1, 1, 28, 28]

# === Run the pipeline ===
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
encoder = Encoder().to(device)
cppn = ConditionalCPPN().to(device)

image = image.to(device)
with torch.no_grad():
    features = encoder(image)  # [1, 8]
    coords = generate_coords(28, batch_size=1).to(device)  # [1, 784, 3]
    output = cppn(coords, features)  # [1, 784]
    output_image = output.view(28, 28).cpu().numpy()

# === Show original and generated image ===
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
axs[0].imshow(image.squeeze().cpu().numpy(), cmap='gray')
axs[0].set_title("Original FashionMNIST")
axs[0].axis('off')

axs[1].imshow(output_image, cmap='gray')
axs[1].set_title("Generated by CPPN")
axs[1].axis('off')

plt.tight_layout()
plt.show()

import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

# Load FashionMNIST dataset
transform = transforms.ToTensor()  # Converts to [C, H, W] with pixel values in [0, 1]
dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
loader = DataLoader(dataset, batch_size=4, shuffle=False)

# Example: Get a batch and map each pixel to (p, 1-p)
for images, labels in loader:
    # images: [B, 1, H, W] -> Remove channel dimension: [B, H, W]
    images = images.squeeze(1)  # Now shape is [B, H, W]

    # Compute x = p, y = 1 - p
    x = images  # [B, H, W]
    y = 1.0 - images  # [B, H, W]

    # Stack along last dimension to get [B, H, W, 2]
    coordinates = torch.stack([x, y], dim=-1)

    print("Shape of coordinates:", coordinates.shape)  # [B, H, W, 2]
    print("Example pixel (0,0) of first image:", coordinates[0, 0, 0])  # [p, 1-p]
    break

from torchvision import datasets
import numpy as np
import matplotlib.pyplot as plt

# Load raw FashionMNIST images as PIL (no transform)
raw_dataset = datasets.FashionMNIST(root='./data', train=False, download=True)

# Search for an image with pixel (0, 0) not equal to 0 or 255
for idx in range(len(raw_dataset)):
    pil_image, label = raw_dataset[idx]
    np_image = np.array(pil_image)

    pixel_val = np_image[0, 0]
    if 0 < pixel_val < 255:
        print(f"Found image at index {idx} with pixel (0, 0) = {pixel_val}")
        break

# Visualize the image
plt.imshow(np_image, cmap='gray')
plt.title(f'Label: {label}, Pixel (0,0) = {pixel_val}')
plt.axis('off')
plt.show()

from torchvision import datasets, transforms
import torch

# Index of the image you found earlier
idx = 5661  # replace with the actual index you found

# Use ToTensor to get normalized pixel values in [0, 1]
transform = transforms.ToTensor()
dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)

# Get image and label
image, label = dataset[idx]  # image: [1, 28, 28]
image = image.squeeze(0)     # [28, 28]

# Create coordinates: each pixel → (p, 1 - p)
x = image
y = 1.0 - image
coords = torch.stack([x, y], dim=-1)  # shape: [28, 28, 2]

# Example: check pixel (0, 0) or others
i, j = 0, 0
print(f"Pixel ({i},{j}): intensity = {x[i,j]:.3f}, 1 - intensity = {y[i,j]:.3f}, coordinate = {coords[i,j]}")



import torch
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import math
from torch.utils.data import random_split, DataLoader, TensorDataset

random_seed = 42

dataset_name= "fashionmnist"
batch_size = 64
input_channels =1
num_classes = 10
train_size_percent = .80
val_size_percent = .10
test_size_percent = .10

def load_dataset(dataset_name, batch_size):

    # Dataset transformations
    if dataset_name.lower() in ["mnist", "fashionmnist"]:
        transform = transforms.Compose([transforms.ToTensor()])
    else:  # CIFAR datasets
        transform = transforms.Compose([
            transforms.RandomCrop(32, padding=4),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010))])

    # Load dataset
    if dataset_name.lower() == "mnist":
        dataset = datasets.MNIST(root="./data", train=True, download=True, transform=transform)
    elif dataset_name.lower() == "fashionmnist":
        dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
    elif dataset_name.lower() == "cifar_10":
        dataset = datasets.CIFAR10(root="./data", train=True, download=True, transform=transform)
    elif dataset_name.lower() == "cifar_100":
        dataset = datasets.CIFAR100(root="./data", train=True, download=True, transform=transform)
    else:
        raise ValueError(f"Unsupported dataset: {dataset_name}. Please choose 'mnist', 'fashionmnist', 'cifar_10', or 'cifar_100'.")

    # Create a DataLoader for the full dataset
    data_loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    return dataset, data_loader


def split_dataset(dataset, batch_size, train_size_percent, val_size_percent):

    # Calculate split sizes
    train_size = int(train_size_percent * len(dataset))
    val_size = int(val_size_percent * len(dataset))
    test_size = len(dataset) - train_size - val_size

    # Split dataset
    train_dataset, val_dataset, test_dataset = random_split(dataset, [train_size, val_size, test_size])

    # Create DataLoaders
    generator = torch.Generator() # added to test if the result will be the same
    generator.manual_seed(random_seed)  # added to test if the result will be the same

    train_loader = DataLoader(train_dataset, generator=generator, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, generator=generator, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, generator=generator, batch_size=batch_size, shuffle=False)


    return train_loader, val_loader, test_loader


# 1. load original dataset
dataset, data_loader = load_dataset(dataset_name=dataset_name, batch_size=batch_size)
train_loader, val_loader, test_loader = split_dataset(dataset=dataset, batch_size=batch_size, train_size_percent=train_size_percent, val_size_percent=val_size_percent)


def image_to_cppn_coords(images, epsilon=1e-6):

    B, C, H, W = images.shape

    # Flatten pixel intensities: [B, C, H, W] → [B, H*W*C]
    pixels = images.permute(0, 2, 3, 1).reshape(B, H * W * C)  # [B, HWC]

    # Compute Y = log(p + epsilon)
    y = torch.log(pixels + epsilon)

    # Compute spatial index X = i * W + j (same for each image)
    spatial_index = torch.arange(H * W, dtype=torch.float32, device=images.device).repeat(C)  # [H*W*C]
    x = spatial_index.unsqueeze(0).expand(B, -1)  # [B, H*W*C]

    # Stack X and Y
    coords = torch.stack([x, y], dim=-1)  # [B, H*W*C, 2]
    return coords, H, W, C

# Example usage inside your training loop

# ==== STEP 3: Define a simple CPPN ====
class SimpleCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 2]
        x = torch.sin(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        out = torch.sigmoid(self.fc3(x))  # Output in [0, 1]
        return out



cppn = SimpleCPPN()
for images, labels in train_loader:
    coords, H, W, C = image_to_cppn_coords(images)  # coords: [1, 784, 2]


    break









# ==== STEP 4: Generate output from CPPN ====
cppn_output = cppn(coords)  # [1, HWC, 1]
image_generated = cppn_output.view(1, C, H, W).detach()  # [1, 1, 28, 28]

# ==== STEP 5: Plot original and CPPN output ====
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
axs[0].imshow(images[0, 0].cpu(), cmap="gray")
axs[0].set_title("Original Image")
axs[0].axis("off")

axs[1].imshow(image_generated[0, 0].cpu(), cmap="gray")
axs[1].set_title("CPPN Output")
axs[1].axis("off")

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# ==== STEP 1: Load FashionMNIST ====
transform = transforms.ToTensor()
dataset = datasets.FashionMNIST(root="./data", train=True, download=True, transform=transform)
data_loader = DataLoader(dataset, batch_size=1, shuffle=True)  # one image for simplicity
images, _ = next(iter(data_loader))  # [1, 1, 28, 28]

# ==== STEP 2: Transform image to CPPN coordinates ====
def image_to_cppn_coords(images, epsilon=1e-6):
    B, C, H, W = images.shape

    # Flatten pixel intensities: [B, C, H, W] → [B, H*W*C]
    pixels = images.permute(0, 2, 3, 1).reshape(B, H * W * C)  # [B, HWC]

    # Compute Y = log(p + epsilon)
    y = torch.log(pixels + epsilon)

    # Compute spatial index X = i * W + j (same for each image)
    spatial_index = torch.arange(H * W, dtype=torch.float32, device=images.device).repeat(C)  # [H*W*C]
    x = spatial_index.unsqueeze(0).expand(B, -1)  # [B, H*W*C]

    # Stack X and Y
    coords = torch.stack([x, y], dim=-1)  # [B, H*W*C, 2]
    return coords, H, W, C

coords, H, W, C = image_to_cppn_coords(images)  # coords: [1, 784, 2]

# ==== STEP 3: Define a simple CPPN ====
class SimpleCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=64, output_dim=1):
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):  # coords: [B, N, 2]
        x = torch.sin(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        out = torch.sigmoid(self.fc3(x))  # Output in [0, 1]
        return out


class EnhancedCPPN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=128, output_dim=1):  # << set input_dim=2
        super().__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, hidden_dim)
        self.fc3 = nn.Linear(hidden_dim, hidden_dim)
        self.fc4 = nn.Linear(hidden_dim, output_dim)

    def forward(self, coords):
        x = torch.sin(self.fc1(coords))
        x = torch.tanh(self.fc2(x))
        x = F.leaky_relu(self.fc3(x), 0.1)
        return torch.sigmoid(self.fc4(x))


def generate_coords_from_flat_index(H, W):
    N = H * W
    indices = torch.arange(N).float().unsqueeze(1)  # shape: [N, 1]
    y = torch.zeros_like(indices)                  # dummy y
    coords = torch.cat([indices, y], dim=1)
    return coords

# ==== Recover (i, j) from x = i * W + j ====
def reconstruct_image_from_cppn_output(output, H, W):

    return output.view(H, W)



#cppn = SimpleCPPN()
cppn = EnhancedCPPN()

# ==== STEP 4: Generate output from CPPN ====
cppn_output = cppn(coords)  # [1, HWC, 1]
image_generated = cppn_output.view(1, C, H, W).detach()  # [1, 1, 28, 28]
#reconstructed = reconstruct_image_from_cppn_output(cppn_output, H, W)



# ==== STEP 5: Plot original and CPPN output ====
fig, axs = plt.subplots(1, 2, figsize=(6, 3))
axs[0].imshow(images[0, 0].cpu(), cmap="gray")
axs[0].set_title("Original Image")
axs[0].axis("off")

axs[1].imshow(image_generated[0, 0].cpu(), cmap="gray")
axs[1].set_title("CPPN Output")
axs[1].axis("off")

plt.tight_layout()
plt.show()